# Generated by Django 5.1.4 on 2025-05-07 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "username",
                    models.EmailField(max_length=50, primary_key=True, serialize=False),
                ),
                ("fullName", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "userDataId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=50, null=True)),
                ("data", models.CharField(max_length=500, null=True)),
                ("date", models.DateField(auto_now=True)),
                (
                    "dataUsername",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LOGIN_Assig.user",
                    ),
                ),
            ],
        ),
    ]
