# Generated by Django 5.1.4 on 2025-07-21 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOGIN_Assig", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdata",
            old_name="dataUsername",
            new_name="Username",
        ),
        migrations.RenameField(
            model_name="userdata",
            old_name="userDataId",
            new_name="toDoListId",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="date",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="title",
        ),
        migrations.AddField(
            model_name="user",
            name="loginTimes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name="WorkDone",
            fields=[
                (
                    "workDoneId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("data", models.CharField(max_length=500, null=True)),
                ("date", models.DateField(auto_now=True)),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LOGIN_Assig.user",
                    ),
                ),
            ],
        ),
    ]
