# Generated by Django 5.1.4 on 2025-07-21 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOGIN_Assig", "0002_rename_datausername_userdata_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToDoListId",
            fields=[
                (
                    "toDoListId",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("data", models.CharField(max_length=500, null=True)),
                (
                    "Username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="LOGIN_Assig.user",
                    ),
                ),
            ],
        ),
    ]
