# Generated by Django 5.1.4 on 2025-07-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOGIN_Assig", "0003_todolistid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdata",
            old_name="toDoListId",
            new_name="UserDataId",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="Username",
        ),
        migrations.RemoveField(
            model_name="userdata",
            name="data",
        ),
    ]
