# Generated by Django 5.1.4 on 2025-07-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOGIN_Assig", "0004_rename_todolistid_userdata_userdataid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolistid",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
