# Generated by Django 5.1.4 on 2025-08-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOGIN_Assig", "0005_todolistid_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserData",
        ),
        migrations.DeleteModel(
            name="WorkDone",
        ),
    ]
