# Generated by Django 5.1.4 on 2025-08-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LOGIN_Assig", "0006_delete_userdata_delete_workdone"),
    ]

    operations = [
        migrations.AddField(
            model_name="todolistid",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
