# Generated by Django 5.1.4 on 2025-08-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LOGIN_Assig", "0007_todolistid_status"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ToDoListId",
            new_name="ToDoList",
        ),
    ]
